### PR TITLE
[RNMobile] Fix Tiled Gallery JS test failure 

### PR DESCRIPTION
**Pull request by guarani**
Fixes failing JS test that was introduced by a bug in https://github.com/Automattic/jetpack/pull/21767/files. The failing test is:

```
  FAIL extensions/blocks/tiled-gallery/layout/mosaic/test/index.js
    ● renders as expected
  
      TypeError: row.querySelectorAll is not a function
  
        58 | function getRowCols( row ) {
        59 | 	return Platform.select( {
      > 60 | 		web: () => Array.from( row.querySelectorAll( '.tiled-gallery__col' ) ),
           | 		                           ^
        61 | 		native: () => row,
        62 | 	} )();
        63 | }
```

#### Changes proposed in this Pull Request:
- Bug fix for the Tiled Gallery on the web (this bug isn't on `master`, it's only on our feature branch).

#### Jetpack product discussion
p9ugOq-1Tb-p2

#### Does this pull request change what data or activity we track or use?
No, it does not.

#### Testing instructions:
Verify that the `JS tests` CI check passes. The "Code coverage" test may fail for different reasons, as long as it doesn't fail due to the above error.

### CODE REVIEW

**Comment by guarani** [comment]
Summary of failing tests:

#### `Tests / PHP tests: PHP 8.1 WP master (pull_request)`

The PHP 8.1 test is optional (see `experimental` keyword [here](https://github.com/Automattic/jetpack/blob/74cb231cc423013ab9e947a65fda7aefe01e472f/.github/files/generate-ci-matrix.php#L66-L71) and [here](https://github.com/Automattic/jetpack/blob/74cb231cc423013ab9e947a65fda7aefe01e472f/.github/files/generate-ci-matrix.php#L41-L42).

#### `Linting / Changelogger use`

We'll be adding the changelog in a future PR to merge the feature branch to `master` (see [this comment](https://github.com/Automattic/jetpack/pull/20925#issuecomment-913854946)).

#### `wpcom — Could not cleanly apply this PR to synced wpcom files`

This is fine to ignore for now since we're merging to a feature branch.

**Review by SiobhyB — APPROVED** [review]
LGTM, thanks for fixing this @guarani 🙇‍♀️
