### PR TITLE
WP.com block editor: Ignore token on cross-site cookies

### LINKED ISSUE #14385: WordPress.com block editor: cannot log in with JP 8.1.1.
This is a regression introduced by #14349. cc @mmtr 

#### Steps to reproduce the issue

1. Start with a site with no SSL certificate, running the most recent version of `master`, including #14349 
2. Log out
3. Clear your cookies for that site.
4. Try to log back in; you'll see that auth cookies cannot be created, and you consequently cannot log in.

### PR DESCRIPTION
**Pull request by mmtr**
Might help solving #14385

#### Changes proposed in this Pull Request:
Our filters hooking into `set_auth_cookie` and `set_logged_in_cookie` were expecting 6 params. The 6th param `$token` was added in WP 4.9.0, so sites using older versions of WP are running into errors when using Jetpack 8.1.1:

```
Uncaught ArgumentCountError: Too few arguments to function Jetpack_WPCOM_Block_Editor::set_samesite_auth_cookies(), 5 passed in /public_html/mu/wp-includes/class-wp-hook.php on line 288 and exactly 6 expected in /public_html/wp-content/plugins/jetpack/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php:451
```

This PR removes that param from the hook callback since it was not used, which effectively fixes the issue with sites using older versions of WP.

It also changes the filter to determine if logged in cookies are secure from `secure_auth_cookie` to `secure_logged_in_cookie` which is the filter used in the original pluggable function. See https://github.com/Automattic/jetpack/issues/14385#issuecomment-578670368. This might solve issues reported in #14385, but we've not found yet exact steps to reproduce them, so we could need more changes.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
p1580764602411500-slack-jetpack-crew

#### Testing instructions:
* Activate Jetpack Beta on a site using WP 4.8 or older.
* Connect Jetpack to WP.com
* Go to Jetpack > Beta and switch to this branch.
* Log out and log in.
* Verify you can log in normally.
* Verify on the browser devtools the auth cookies are created as `SameSite: None`.

#### Proposed changelog entry for your changes:
N/A

### CODE REVIEW

**Review by zinigor — APPROVED** [review]
Works well for me!

**Comment by jeherve** [comment]
Cherry-picked to `branch-8.2` in 1b0c380bcc3461531afdb6534b23bbceda8fa18a
