### ISSUE TITLE
Form Block: "This block has encountered an error and cannot be previewed."

### ISSUE THREAD

**Issue by retnonindya** [Automattic/jetpack#34847]
### Impacted plugin

Jetpack

### Quick summary

The Form Block is not working on **Atomic (WoA) site.** When added the Form Block to page/post editor, the block displays the error "This block has encountered an error and cannot be previewed." The error persists on Troubleshooting Mode and only Jetpack plugin active with WPCOM theme.

### Steps to reproduce

**AT site only:**
1. Create/edit a page
2. Add a block: Form Block
3. See the error
<img width="665" alt="image" src="https://github.com/Automattic/jetpack/assets/87168/ec12bd81-1287-4e22-ad3b-0376c7667336">

This also affects all form-related blocks:
![Screenshot 2024-01-04 at 10 33 31 AM](https://github.com/Automattic/jetpack/assets/44726232/d3ec3845-d7ce-4622-96d0-c7bf8e78ed7d)

(Hover your mouse on the block, and you will see the preview displays the error too.)

### A clear and concise description of what you expected to happen.

The Form Block should work and displays the form that the user can manage. 

### What actually happened

The block is not visible and displaying "This block has encountered an error and cannot be previewed." error

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

If the page has an existing working Form Block, the form will be visible on the live site -- but not working on the editor.

Errors when testing locally:

<img width="2289" alt="Screenshot 2024-01-04 at 13 43 37" src="https://github.com/Automattic/jetpack/assets/87168/27b61eed-1de2-4068-a6e9-be984dedbf7b">
<img width="1039" alt="Screenshot 2024-01-04 at 13 43 07" src="https://github.com/Automattic/jetpack/assets/87168/03aeac0b-d018-4185-9103-290b40b034c2">

Possibly caused by https://github.com/Automattic/jetpack/pull/34801

**Comment by retnonindya** [comment]
User report: 7531598-zen

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##

- Tested on Atomic – 
Replicated with theme "Course" and "Programme"
But not replicated with "Amulet" where it works 

- Tested on Simple – Could Not Replicate with any theme

Conclusion: Looks like an Atomic issue.

##Workarounds:## 
None beyond changing themes

## 📌 ACTIONS ##
Triaged

**Comment by Aurorum** [comment]
```
edit.js:413 Uncaught TypeError: isModuleUpdating is not a function
    at edit.js:413:22
    at mapSelect (data.js?ver=2b5bb06caaeb5048ed96:4285:43)
    at data.js?ver=2b5bb06caaeb5048ed96:4073:70
```

cc @andrii-lysenko - looks like it might be a defect of #34801?

**Comment by liviopv** [comment]
- [ ] 7533020-zd-a8c

**Comment by liviopv** [comment]
Reproduced it on a Pressable Site, but not on a local site and jurassic.ninja, so this is contained to Atomic sites.

**Comment by liviopv** [comment]
Escalation thread: p1704367982178349-slack-C02FMH4G8

**Comment by dsas** [comment]
It's reproducible on jurassic ninja if using the Jetpack RC - 13.0-a11 which is the same as is used on atomic sites.

**Comment by simison** [comment]
Reproduced locally with Jetpack `trunk`, included screenshots of console errors.

**Comment by mikeicode** [comment]
We use this block on all of our builds (BBE) and are running into this on AT sites.

**Comment by zdenys** [comment]
- [ ] 7533524-zd-a8c Let's follow up with the user please

**Comment by jackiejade** [comment]
This is also affecting some of our Built By premium sites.
7530703-zd-a8c

**Comment by andrii-lysenko** [comment]
> Reproduced locally with Jetpack trunk, including screenshots of console errors.

@simison could you please provide more details on this one?

**Comment by anomiex** [comment]
Summary of the cause of the problem:

* #34801 made a change in one of the data stores, renaming one of the selectors.
  * This change [was marked as semver "patch"-level significance](https://github.com/Automattic/jetpack/blob/720acc1a5424c2a6105242110814ec43c6b9766f/projects/js-packages/shared-extension-utils/changelog/enhance-modules-store-loading-updating#L1). A removal of an existing selector name should probably have been "major".
* That selector is not used in packages/videopress, so no change was made to that package.
* There were also no other changes to packages/videopress between a.9 and a.11.
* Since there were no changes in packages/videopress itself, version 0.21.6 (that still bundled the old version of the data store) was reused instead of building a new 0.21.7.
  * If the change to the JS package had been marked as major, our release tooling [would have forced a rebuild of the package anyway](https://github.com/Automattic/jetpack/blob/238b2f4e519dd7aecab4d34e2cd41817fbb8e350/tools/changelogger-release.sh#L220-L232).
* Data store registration is "first module to register wins" (see also #34793). Which happenes to be packages/videopress for this store.
* Thus, when code that actually does use the renamed selector tried to use it, it couldn't find it because the store came from a module that bundles the old version.

**Comment by simison** [comment]
@andrii-lysenko I might've just built forms package when testing trunk and saw the error locally; building entire jetpack with deps might've made the error go away locally.

**Comment by andrii-lysenko** [comment]
@simison Thanks for the context. Yes, this one was very tricky.

**Comment by ekarpuk** [comment]
I have a Built By Client that seems to still be experiencing this issue. 

[SA](https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=zarisadeq
)

Site - https://cnib-accesslabs.ca/

**Comment by andrii-lysenko** [comment]
@ekarpuk can we make sure that it's not a cache issue (maybe ask them to clean cache) as the version was actually reverted: p1704391227017289/1704391119.565089-slack-C05Q5HSS013

**Comment by ekarpuk** [comment]
@andrii-lysenko , the client is still getting the same error after clearing/cleaning their cache.

**Comment by andrii-lysenko** [comment]
@ice9js @anomiex Do you have any ideas on this one?

**Comment by anomiex** [comment]
When I look at https://cnib-accesslabs.ca/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-forms/dist/blocks/editor.js it seems they have the [a.9](https://github.com/Automattic/jetpack-production/blob/13.0-a.9/jetpack_vendor/automattic/jetpack-forms/dist/blocks/editor.js) version of the file as expected, not the [a.11](https://github.com/Automattic/jetpack-production/blob/13.0-a.11/jetpack_vendor/automattic/jetpack-forms/dist/blocks/editor.js) version. Specifically, I see "areModulesUpdating" rather than "isModuleUpdating" in the middle of it.

**Comment by ekarpuk** [comment]
@anomiex , would that be related to the site build or this error? I'm not familiar enough with this functionality to know next steps for the client. Thank you!

**Comment by anomiex** [comment]
@ekarpuk My guess is that either they have some sort of cache that hasn't been cleared or that the problem they're seeing isn't the same one that this issue is about.

The fact that the file I linked was showing the a.9 version of the code is a good indicator that their Atomic site was rolled back along with all the others. OTOH, a.13 was just deployed a few minutes ago now, which includes the new stuff from a.11 and additionally fixes the cause of this problem.

**Comment by jeherve** [comment]
@ekarpuk I'll close this issue now, since the site now runs `13.0-a.13`. They should not be experiencing the issue anymore.
